# Generated by Django 5.1.4 on 2025-03-01 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customuser', 'CustomUser'), ('accountant', 'Accountant'), ('admin', 'Admin')], default='customuser', max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('company_key', models.CharField(max_length=50, unique=True)),
                ('company_type', models.CharField(choices=[('LLC', 'MChJ'), ('SP', 'XK'), ('JSC', 'AJ')], max_length=50)),
                ('company_activity', models.CharField(max_length=255)),
                ('legal_address', models.TextField()),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_mfo', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_system', models.CharField(choices=[('general', 'Umumiy'), ('simplified', 'Soddalashtirilgan')], max_length=50)),
                ('is_vat_payer', models.BooleanField(default=False)),
                ('service_type', models.CharField(max_length=255)),
                ('document_count', models.PositiveIntegerField()),
                ('order_deadline', models.DateField()),
                ('additional_files', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
