# Generated by Django 5.1.4 on 2025-03-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(choices=[('6262570125113045', '6262570125113045'), ('3654263263263267', '3654263263263267')], max_length=16)),
                ('status', models.CharField(choices=[('boshlandi', 'Boshlandi'), ('tekshirilmoqda', 'Tekshirilmoqda'), ('tugatildi', 'Tugatildi')], default='boshlandi', max_length=20)),
            ],
        ),
    ]
