# Generated by Django 5.1.4 on 2025-02-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_royxate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='xizmatlar/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Royxate',
        ),
    ]
