# Generated by Django 5.1.4 on 2025-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_xizmatlar_delete_royxate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narxlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=70)),
                ('offer_two', models.CharField(max_length=70)),
                ('offer_three', models.CharField(max_length=70)),
                ('offer_four', models.CharField(max_length=70)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
